name=pwmWav
version=1.0
author=Sajed hashemi <sajed.sp2006@hotmail.com>
maintainer=Sajed hashemi <sajed.sp2006@hotmail.com>
sentence=Play WAV file from SPIFFS
paragraph= Play WAV file from SPIFFS. support ESP32 platform.
category=pwm
url=https://github.com/SajedHashemi/pwmWav
architectures=esp32
includes=pwmWav.h
